version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/graphics-generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "00:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 2
    labels:
      - infra
    rebase-strategy: disabled