name: perf-job-pr-automerge.yml

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: (github.actor == 'quarkusbot') && contains(github.event.pull_request.labels.*.name, 'perf-lab-run') && startsWith(github.head_ref, 'upload-results-')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:    
      - name: Automerge PR
        run: gh pr merge --merge --delete-branch "$PR_URL"
